Open-Pix/openpix-developers

docs/webhook/webhook-samples.mdx
package.json
yarn.lock

feat(refund): docs

---

docusaurus.config.js
src/swaggers/bacen-pix.yml

[This is the really diff line](https://github.com/Open-Pix/developers/blob/53016b5d9e03fa46dddebe890c15644b34edc003/src/swaggers/bacen-pix.yml#L25)

docs(openpix): add a link to OpenPix API inside BACEN Pix swagger documentation

---

docs/concepts/idempotence.md

Added an article on idempotency.

feat(doc): added idempotency doc

---

docs/webhook/examples/languages.mdx

resolve: https://github.com/entria/woovi/issues/44756

feat(languages): how to intercept an webhook with php

---

docs/sdk/php/_category_.json
docs/sdk/php/customized-http-requests.md
docs/sdk/php/resources.md
docs/sdk/php/usage.md
docs/sdk/php/what-is-php-sdk.md

feat(sdk/php): Add PHP-SDK docs

---

docs/sdk/php/resources.md

new release: https://github.com/Open-Pix/php-sdk/releases/tag/v1.1.0

docs(sdk/php): add docs for webhook validation method

---

docs/integrations/oneclick.md

resolve https://github.com/entria/woovi/issues/51789

feat(oneclick): how to integrate with openpix

---

docs/subaccount/_category_.json
docs/subaccount/how-to-create-charge-with-splits-to-subaccount-using-api.mdx
docs/subaccount/how-to-get-balance-and-detais-of-subaccount-using-api.mdx
docs/subaccount/how-to-list-subaccounts-of-company-using-api.mdx
docs/subaccount/how-to-withdraw-fom-subaccount-using-api.mdx

https://github.com/entria/woovi/issues/56186

feat(subaccount): add docs how to and tab

---

docs/subaccount/sub-account-use-cases.md
docs/subaccount/sub-account.md
docs/subaccount/when-to-use-subaccount-or-partner.md

https://github.com/entria/woovi/issues/56264

feat(subaccount): concepts.

---

docs/sdk/php/frameworks/laravel/example-integration.md

fix(id): fix wrong id of page

---

docs/transaction/transaction-how-to-paginate-api.md

feat(transaction): how to paginate api

---

docs/ecommerce/opencart/opencart3-extension.mdx
docs/ecommerce/opencart/opencart4-extension.mdx

fix(opencart): wrong cautions

---

i18n/en/docusaurus-plugin-content-docs/current/plugin/plugin-react.md

https://github.com/Open-Pix/openpix-developers/issues/893

fix(react): use yarn add on english page

---

docs/sdk/node/_category_.json
docs/sdk/node/error-handling.md
docs/sdk/node/resources.md
docs/sdk/node/usage.md
docs/sdk/node/what-is-node-sdk.md

this pull request will add a docs for nodejs sdk that is under development on https://github.com/sibelius/woovi-nodejs-sdk

docs(node-sdk): implement docs for node sdk(under development)

---

docs/webhook/examples/dispute-accept-payload.mdx
docs/webhook/examples/dispute-canceled-payload.mdx
docs/webhook/examples/dispute-payload.mdx
docs/webhook/examples/dispute-rejected-payload.mdx

https://github.com/entria/woovi/issues/71346

feat(doc) add dispute webhook example payload

---

src/swaggers/openpix.json
src/swaggers/openpix.yml

https://github.com/entria/woovi/issues/71346

feat(dispute) improve doc

---

src/swaggers/openpix.json
src/swaggers/openpix.yml

https://github.com/entria/woovi/issues/71346

fix(status) change order

---

src/swaggers/openpix.json
src/swaggers/openpix.yml

feat(customer) add taxID to example doc

---

docusaurus.config.js

fix(build): disable build en page

---

docusaurus.config.js

Close: https://github.com/entria/woovi/issues/76126
We are not translating and using the docusaurus translation correctly
Read: https://v1.docusaurus.io/docs/pt-br/translation

fix(build): fix build

---

docusaurus.config.js

fix(doc): fix doc search

---

i18n/pt-BR/code.json
i18n/pt-BR/docusaurus-plugin-content-blog/options.json
i18n/pt-BR/docusaurus-plugin-content-docs/current.json
i18n/pt-BR/docusaurus-theme-classic/footer.json
i18n/pt-BR/docusaurus-theme-classic/navbar.json

fix(search): try fix search

---

docusaurus.config.js

Reverts Open-Pix/openpix-developers#953

Revert "fix(locales): update locales"

---

docs/cashback-fidelity/_category_.json
docs/cashback-fidelity/cashback-fidelity-apis.md
docs/cashback-fidelity/cashback-fidelity-how-to-build-customer-fidelity.md
docs/cashback-fidelity/cashback-fidelity-how-to-config.md
docs/cashback-fidelity/cashback-fidelity-how-to-use.md
docs/cashback-fidelity/cashback-fidelity-what-is.md
docs/sdk/node/resources.md
i18n/en/docusaurus-plugin-content-docs/current/cashback-fidelity/cashback-fidelity-apis.md
i18n/en/docusaurus-plugin-content-docs/current/cashback-fidelity/cashback-fidelity-how-to-build-customer-fidelity.md
i18n/en/docusaurus-plugin-content-docs/current/cashback-fidelity/cashback-fidelity-how-to-config.md
i18n/en/docusaurus-plugin-content-docs/current/cashback-fidelity/cashback-fidelity-how-to-use.md
i18n/en/docusaurus-plugin-content-docs/current/cashback-fidelity/cashback-fidelity-what-is.md

feat(cashback) change from fidelity to proxima compra

---

docs/integrations/integrating-openpix-with-shop9.md

fix(doc)update the integration name

---

docs/clickpix/customizing-click-pix-button.md

ref: https://github.com/entria/woovi/issues/79571

fix adjust docs customizing clickpix button steps

---

docs/intro/test-environment.md
src/pages/index.tsx
src/swaggers/openpix.json

close: https://github.com/entria/woovi/issues/81522
preview:

feat(doc): simple doc for sandbox environment

---

docs/disputa/how-add-new-evidence-in-evidence.md

issue: https://github.com/entria/woovi/issues/87038

add doc upload dispute evidence

---

src/css/custom.css

fix: added css styling forcing background color

---

docs/partnerships/how-to-create-a-affiliate-company-via-api.md

ref: https://github.com/entria/woovi/issues/85182

fix: api url create affialite company
